server:
  port: 8888
spring:
  cloud:
    config:
        server:
           git:
             username: nikhil
             uri: https://github.com/Nikhil-Umesh/cloud-config
             searchPaths: '{application}/{profile}'
             clone-in-start: true
