server.port: 8888
spring:
  cloud:
    config:
        server:
           git:
             uri: https://github.com/Nikhil-Umesh/cloud-config
             username: arnav
             password: sweety